// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluehhkpoqflguubxjgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdWVoaGtwb3FmbGd1dWJ4amdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMzMzOTcsImV4cCI6MjA1MDYwOTM5N30.h_79o_RTICU9pbBo3hb6Zr2kwibMqvUmTqBSwnpyzWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);